[env:m5stack-cores3]
platform = espressif32@7.0.1
board = m5stack-cores3
framework = arduino

monitor_speed = 115200
upload_protocol = esptool
upload_speed = 115200

lib_deps =
    m5stack/M5GFX@0.2.28
    m5stack/M5Unified@0.2.21
    lvgl/lvgl@9.5.0
    bblanchon/ArduinoJson@7.4.3
    mikalhart/TinyGPSPlus@1.1.0

build_flags =
    -I${platformio.include_dir}
    -DLV_CONF_INCLUDE_SIMPLE
    -DLV_DISABLE_API_MAPPING
    -DEV_LOG_TRY_SD=0
    -DEV_ENABLE_SENSORS=1
    -DEV_SENSORS_DETECT_ONLY=0
    -DEV_I2C_SCAN=0
    -DEV_NTC_COUNT=1
